export const Message = {
  MAGIC_LINK_SENT: 'Magic Link has been sent!🚀',
  ACCOUNT_CREATION_SUCCESS:
    'Account Created Successfully 🚀 Please check your email',
  LOGIN_SUCCESS: 'Login Successfully 🚀',
  ACCOUNT_FOUND: 'Account Found! 😊',
  ACCOUNT_UPDATED: 'Account updated !',
  DEVICES_RETRIVED: 'Devices found',
  DEVICE_CREATED: 'Device Created successfully',
  DEVICE_UPDATED: 'Device Updated successfully',
  DEVICE_STATUS_UPDATED: 'Device Status Updated successfully',
  DEVICE_DELETED: 'Device Deleted successfully',
  DEVICE_FOUND: 'Device Found successfully',
  DEVICE_NOT_FOUND: 'Device Not Found successfully',
  DEVICE_ALREADY_EXIST: 'Device Already Exist successfully',
  DEVICE_NOT_EXIST: 'Device Not Exist successfully',
  DEVICE_BLOCKED: 'Device Blocked successfully',
  DEVICE_UNBLOCKED: 'Device Unblocked successfully',
  DEVICE_LOGOUT: 'Device Logout successfully',
  DEVICE_LOGOUT_ALL: 'Device Logout All successfully',
  DEVICE_LOGOUT_OTHERS: 'Device Logout Others successfully',
  DEVICE_LOGOUT_CURRENT: 'Device Logout Current successfully',
  DEVICE_LOGOUT_EXPIRED: 'Device Logout Expired successfully',
  DEVICE_LOGOUT_NOT_FOUND: 'Device Logout Not Found successfully',
  DEVICE_LOGOUT_INVALID: 'Device Logout Invalid successfully',
  DEVICE_LOGOUT_UNAUTHORIZED: 'Device Logout Unauthorized successfully',
  DEVICE_LOGOUT_FORBIDDEN: 'Device Logout Forbidden successfully',
  DEVICE_LOGOUT_NOT_ACCEPTABLE: 'Device Logout Not Acceptable successfully',
  DEVICE_LOGOUT_TOO_MANY_REQUESTS:
    'Device Logout Too Many Requests successfully',
  DEVICE_LOGOUT_INTERNAL_SERVER_ERROR:
    'Device Logout Internal Server Error successfully',
};
